apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-backend: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: passwd
          image: shichoc/mysqlshop
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            timeoutSeconds: 20
          name: database
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
