apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: myapp
  name: lb-myapp
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: myapp
  type: LoadBalancer
status:
  loadBalancer: {}
